-- ===========================================
-- Firebird Database Schema Export
-- ===========================================

CREATE TABLE ABONOS (
    ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER,
    DTFECHA TIMESTAMP,
    DMONTO FLOAT,
    BCONTAR CHAR(1),
    GANANCIA FLOAT,
    ID_TURNO INTEGER,
    FORMA_DE_PAGO CHAR(10),
    DEVUELTO_EN TIMESTAMP,
    ID_CAJA INTEGER,
    FACTURA_ID INTEGER,
    IMPUESTOS_COBRADOS VARCHAR(255) NOT NULL,
    PAGADO_EN TIMESTAMP,
    CLIENTESV2_CREDITO_ID INTEGER
);

CREATE TABLE ABONOS_ARTICULOS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    ARTICULO_ID INTEGER NOT NULL,
    PORCENTAJE_PAGADO INTEGER
);

CREATE TABLE ABONOS_VENTAS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    TICKET_ID INTEGER NOT NULL,
    MONTO_ABONADO FLOAT NOT NULL,
    CONSECUTIVO SMALLINT,
    SALDO_ANTERIOR FLOAT,
    SALDO_POSTERIOR FLOAT,
    CANCELADO_EN TIMESTAMP
);

CREATE TABLE ABONO_TICKETS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    TICKET_ID INTEGER NOT NULL,
    ARTICULO_ID INTEGER NOT NULL,
    PORCENTAJE_PAGADO FLOAT NOT NULL,
    ABONO_GANANCIA FLOAT NOT NULL,
    ABONO_GANANCIA_DEPTO_ID INTEGER NOT NULL,
    ABONO_IMPORTE FLOAT NOT NULL,
    ABONO_IMPUESTOS_TOTAL FLOAT NOT NULL
);

CREATE TABLE ALMACENES (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(255)
);

CREATE TABLE ARTICULOS_DE_OC (
    ID INTEGER NOT NULL,
    ID_ORDEN_DE_COMPRA INTEGER,
    ID_PRODUCTO INTEGER,
    CODIGO_PRODUCTO VARCHAR(20),
    DESCRIPCION_PRODUCTO VARCHAR(255),
    DEPARTAMENTO_PRODUCTO VARCHAR(50),
    CANTIDAD_ORDENADA DOUBLE PRECISION,
    CANTIDAD_RECIBIDA DOUBLE PRECISION,
    ID_AGRUPACION TIMESTAMP,
    COSTO_AL_ORDENAR FLOAT,
    COSTO_AL_RECIBIR FLOAT,
    DIAS_EN_SURTIR FLOAT,
    LISTA_IMPUESTOS VARCHAR(255),
    UTILIDAD_ESTIMADA_AL_ORDENAR FLOAT,
    UTILIDAD_ESTIMADA_AL_RECIBIR FLOAT,
    IMPUESTOS_AL_RECIBIR FLOAT,
    SUBTOTAL_AL_RECIBIR FLOAT,
    TOTAL_AL_ORDENAR FLOAT,
    TOTAL_AL_RECIBIR FLOAT,
    PRECIO_SIN_IMPUESTOS FLOAT,
    PRECIO_CON_IMPUESTOS FLOAT,
    PRECIO_MAYOREO_CON_IMPUESTOS FLOAT
);

CREATE TABLE ARTICULO_COMPONENTES (
    ARTICULO_ID INTEGER NOT NULL,
    PRODUCTO_PADRE_ID INTEGER NOT NULL,
    PRODUCTO_HIJO_ID INTEGER NOT NULL,
    CANTIDAD FLOAT NOT NULL
);

CREATE TABLE CACHE (
    ID INTEGER NOT NULL,
    PARAMETRO VARCHAR(50),
    VALOR BLOB,
    TTL TIMESTAMP,
    ETAG VARCHAR(50)
);

CREATE TABLE CAJAS (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    ULTIMA_IP VARCHAR(50) NOT NULL,
    ULTIMO_INGRESO TIMESTAMP,
    NOMBRE_PC VARCHAR(255),
    ELIMINADA_EN TIMESTAMP,
    ES_PRINCIPAL CHAR(1),
    TERMINAL_ID VARCHAR(40)
);

CREATE TABLE CLIENTES (
    NUMERO INTEGER NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(50),
    DSALDOACTUAL FLOAT,
    DTACTUALIZASALDO DATE,
    LIMITE_CREDITO FLOAT,
    ULTIMO_PAGO_EN TIMESTAMP,
    FOLIO INTEGER NOT NULL,
    NOMBRE VARCHAR(255)
);

CREATE TABLE CLIENTESV2 (
    ID INTEGER NOT NULL,
    FOLIO INTEGER,
    NOMBRES VARCHAR(255) NOT NULL,
    APELLIDOS VARCHAR(255),
    EMAIL VARCHAR(255),
    TELEFONO VARCHAR(50),
    DOMICILIO1 VARCHAR(255),
    DOMICILIO2 VARCHAR(255),
    COLONIA VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    ESTADO VARCHAR(255),
    PAIS VARCHAR(255),
    CODIGO_POSTAL VARCHAR(20),
    NOTAS VARCHAR(1000),
    TOTAL_VENTAS NUMERIC,
    TOTAL_GANANCIAS NUMERIC,
    TOTAL_TICKETS INTEGER,
    ACTIVO SMALLINT,
    DE_SISTEMA SMALLINT,
    OLD_CLIENTE_ID INTEGER,
    OLD_FACTURACION_CLIENTES_ID INTEGER
);

CREATE TABLE CLIENTESV2_CREDITO (
    CLIENTESV2_ID INTEGER NOT NULL,
    TIENE_CREDITO SMALLINT,
    LIMITE_CREDITO NUMERIC,
    ULTIMO_ABONO TIMESTAMP,
    SALDO_ACTUAL NUMERIC,
    ELIMINADO_EN TIMESTAMP
);

CREATE TABLE CLIENTESV2_FACTURACION (
    CLIENTESV2_ID INTEGER NOT NULL,
    RFC VARCHAR(13) NOT NULL,
    NOMBRE VARCHAR(255),
    CALLE VARCHAR(1000),
    NOEXTERIOR VARCHAR(50),
    NOINTERIOR VARCHAR(50),
    COLONIA VARCHAR(255),
    LOCALIDAD VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    ESTADO VARCHAR(50),
    PAIS VARCHAR(255),
    EMAIL VARCHAR(255),
    REFERENCIA VARCHAR(255),
    CODIGOPOSTAL INTEGER,
    REGIMENES BLOB,
    ELIMINADO_EN TIMESTAMP,
    REGIMEN_FISCAL VARCHAR(50)
);

CREATE TABLE CLIENTESV2_TAGS (
    CLIENTESV2_ID INTEGER NOT NULL,
    TAG VARCHAR(50) NOT NULL
);

CREATE TABLE COMISIONES_TARJETA (
    ID INTEGER NOT NULL,
    TICKET_ID INTEGER,
    ABONO_ID INTEGER,
    TOTAL_COBRADO FLOAT NOT NULL,
    BASE_COMISION FLOAT NOT NULL,
    PORCENTAJE_COMISION SMALLINT NOT NULL,
    MONTO_COMISION FLOAT NOT NULL
);

CREATE TABLE CONCILIACION_PAGO_SERVICIOS (
    ID INTEGER NOT NULL,
    NOMBRE_ARCHIVO VARCHAR(50),
    SUBIDO_EN TIMESTAMP,
    PROCESADO_EN TIMESTAMP,
    CONTENIDO BLOB
);

CREATE TABLE CONFIGURACION (
    ID INTEGER NOT NULL,
    PARAMETRO VARCHAR(255),
    CAJA_ID INTEGER,
    VALOR BLOB
);

CREATE TABLE CORTE_IMPUESTOS_COBRADOS (
    ID INTEGER NOT NULL,
    ID_IMPUESTO INTEGER NOT NULL,
    ACUMULADO_IMPUESTOS NUMERIC,
    ACUMULADO_VENTAS_GRAVADAS NUMERIC,
    ID_TURNO INTEGER NOT NULL,
    ACUMULADO_IMPUESTOS_NO_DESG NUMERIC
);

CREATE TABLE CORTE_IMP_COBRADOS_OPERACION (
    ID INTEGER NOT NULL,
    ID_IMPUESTO INTEGER,
    ACUMULADO_IMPUESTOS NUMERIC,
    ACUMULADO_VENTAS_GRAVADAS NUMERIC,
    ID_OPERACION INTEGER NOT NULL,
    ACUMULADO_IMPUESTOS_NO_DESG NUMERIC
);

CREATE TABLE CORTE_MOVIMIENTOS (
    ID INTEGER NOT NULL,
    BORRADO_EL TIMESTAMP,
    CUANDO_FUE TIMESTAMP,
    MONTO NUMERIC NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    TIPO VARCHAR(50),
    ID_TURNO INTEGER,
    FORMA_PAGO CHAR(1),
    RAZON_DEVOLUCION CHAR(1),
    ID_CAJA INTEGER
);

CREATE TABLE CORTE_OPERACIONES (
    ID INTEGER NOT NULL,
    DIA TIMESTAMP NOT NULL,
    ID_CAJA INTEGER,
    ACUMULADO_VENTAS NUMERIC,
    ACUMULADO_ENTRADAS NUMERIC,
    ACUMULADO_SALIDAS NUMERIC,
    ACUMULADO_GANANCIA NUMERIC,
    VENTAS_EFECTIVO NUMERIC,
    VENTAS_TARJETA NUMERIC,
    VENTAS_VALES NUMERIC,
    VENTAS_CREDITO NUMERIC,
    ABONOS_EFECTIVO NUMERIC,
    DEVOLUCIONES_VENTAS_EFECTIVO NUMERIC,
    DEVOLUCIONES_VENTAS_CREDITO NUMERIC,
    DEVOLUCIONES_ABONOS_EFECTIVO NUMERIC,
    NUMERO_VENTAS INTEGER,
    DEVOLUCIONES_VENTAS_VALES NUMERIC,
    ABONOS_TARJETA NUMERIC,
    ABONOS_VALES NUMERIC,
    COMISIONES_TARJETA FLOAT,
    DEVOLUCIONES_VENTAS_TARJETA NUMERIC NOT NULL,
    VENTAS_TRANSFERENCIA NUMERIC,
    ABONOS_TRANSFERENCIA NUMERIC,
    VENTAS_CHEQUE NUMERIC,
    ABONOS_CHEQUE NUMERIC,
    DEVOLUCIONES_VENTAS_TRANS NUMERIC,
    DEVOLUCIONES_VENTAS_CHEQUE NUMERIC
);

CREATE TABLE CORTE_VENTAS_DEPTO_OPERACIONES (
    ID INTEGER NOT NULL,
    ID_DEPARTAMENTO INTEGER,
    ACUMULADO_VENTAS FLOAT,
    ID_OPERACION INTEGER,
    ACUMULADO_GANANCIAS NUMERIC
);

CREATE TABLE CORTE_VENTAS_POR_DEPTO (
    ID INTEGER NOT NULL,
    ID_DEPARTAMENTO INTEGER,
    ACUMULADO_VENTAS FLOAT,
    ID_TURNO INTEGER,
    ACUMULADO_GANANCIAS NUMERIC
);

CREATE TABLE CREDITOS_ABONOS (
    ID INTEGER NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    MONTO FLOAT,
    NOTA BLOB,
    FORMA_PAGO CHAR(10),
    FACTURA_ID INTEGER,
    CANCELADO_EN TIMESTAMP,
    OLD_ABONO_ID INTEGER
);

CREATE TABLE CREDITOS_ABONOS_ARTICULOS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    ARTICULO_ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    MONTO_ACREDITADO FLOAT,
    GANANCIA_ACREDITADA FLOAT
);

CREATE TABLE CREDITOS_ABONOS_IMPUESTOS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    IMPUESTO_ID INTEGER NOT NULL,
    IMPUESTO_PORCENTAJE FLOAT NOT NULL,
    IMPUESTO_BASE FLOAT,
    IMPUESTO_MONTO FLOAT
);

CREATE TABLE CREDITOS_ABONOS_PAGOS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    FORMA_PAGO CHAR(10),
    COMISIONES_ABONO_ID INTEGER,
    REFERENCIA BLOB,
    TIPO_ABONO INTEGER,
    CAMBIO FLOAT,
    CAMBIO_EN_DOLARES FLOAT,
    PAGO_CON FLOAT,
    ID_SOLICITUD_TERMINAL INTEGER
);

CREATE TABLE CREDITOS_ABONOS_VENTAS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    MONTO_ACREDITADO FLOAT,
    GANANCIA_ACREDITADA FLOAT
);

CREATE TABLE CREDITOS_ARTICULOS_IMPUESTOS (
    ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    ARTICULO_ID INTEGER NOT NULL,
    IMPUESTO_ID INTEGER NOT NULL,
    IMPUESTO_PORCENTAJE FLOAT NOT NULL,
    IMPUESTO_BASE FLOAT,
    IMPUESTO_MONTO FLOAT
);

CREATE TABLE CREDITOS_TRANSACCIONES (
    ID INTEGER NOT NULL,
    FECHA TIMESTAMP NOT NULL,
    TIPO_MOVIMIENTO VARCHAR(50) NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    TURNO_ID INTEGER NOT NULL,
    CLIENTE_ID INTEGER NOT NULL,
    SALDO_AL_MOMENTO FLOAT,
    MONTO_DEL_MOVIMIENTO FLOAT,
    CAJERO_ID INTEGER NOT NULL,
    CAJA_ID INTEGER NOT NULL,
    DEVOLUCION_ID INTEGER
);

CREATE TABLE DEPARTAMENTOS (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PORCENTAJE_IMPUESTO SMALLINT,
    ACTIVO CHAR(1)
);

CREATE TABLE DEPTS (
    NUM INTEGER NOT NULL,
    NOMBRE VARCHAR(50)
);

CREATE TABLE DEVOLUCIONES (
    ID INTEGER NOT NULL,
    TURNO_ID INTEGER,
    TICKET_ID INTEGER,
    TIPO_DEVOLUCION CHAR(1),
    PAGADO_EN TIMESTAMP,
    DEVUELTO_EN TIMESTAMP,
    CAJERO VARCHAR(50),
    CAJA VARCHAR(50),
    TOTAL_DEVUELTO FLOAT,
    SINCRONIZADO_EN TIMESTAMP
);

CREATE TABLE DEVOLUCIONES_ARTICULOS (
    ID INTEGER NOT NULL,
    TICKET_ID INTEGER,
    CODIGO_PRODUCTO VARCHAR(20),
    DESCRIPCION_PRODUCTO VARCHAR(255),
    CANTIDAD_DEVUELTA DOUBLE PRECISION,
    DINERO_DEVUELTO FLOAT,
    INVENTARIO_POST_DEVOLUCION DOUBLE PRECISION,
    DEVOLUCION_ID INTEGER NOT NULL
);

CREATE TABLE DEVOLUCIONES_MERCADOPAGO (
    ID INTEGER NOT NULL,
    TRANSACCION_ID INTEGER NOT NULL,
    REFUND_ID BIGINT NOT NULL,
    PAYMENT_ID BIGINT NOT NULL,
    MONTO FLOAT NOT NULL,
    MONTO_DEVUELTO_PAGADOR FLOAT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    MODO_DEVOLUCION VARCHAR(20),
    RAZON VARCHAR(255),
    REQUEST_ID VARCHAR(100),
    RAW_REQUEST BLOB,
    RAW_RESPONSE BLOB,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(255)
);

CREATE TABLE FACTURACION_CERTIFICADOS (
    ID INTEGER NOT NULL,
    EMISOR_ID INTEGER NOT NULL,
    NUMERO_SERIE VARCHAR(255) NOT NULL,
    VIGENCIA_INICIO TIMESTAMP NOT NULL,
    VIGENCIA_FIN TIMESTAMP NOT NULL,
    CLAVE_LLAVE_PRIVADA VARCHAR(255) NOT NULL,
    CONTENIDO_CERTIFICADO BLOB,
    CONTENIDO_LLAVEPRIVADA BLOB
);

CREATE TABLE FACTURACION_CLIENTES (
    ID INTEGER NOT NULL,
    RFC VARCHAR(13),
    NOMBRE VARCHAR(255),
    CALLE VARCHAR(255),
    NOEXTERIOR VARCHAR(50),
    NOINTERIOR VARCHAR(50),
    COLONIA VARCHAR(255),
    LOCALIDAD VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    ESTADO VARCHAR(50),
    PAIS VARCHAR(255),
    EMAIL VARCHAR(255),
    REFERENCIA VARCHAR(255),
    CODIGOPOSTAL INTEGER,
    REGIMENES BLOB,
    ELIMINADO_EN TIMESTAMP
);

CREATE TABLE FACTURACION_EMISORES (
    ID INTEGER NOT NULL,
    RFC VARCHAR(13),
    NOMBRE VARCHAR(255),
    CALLE VARCHAR(255),
    NOEXTERIOR VARCHAR(50),
    NOINTERIOR VARCHAR(50),
    COLONIA VARCHAR(255),
    LOCALIDAD VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    ESTADO VARCHAR(50),
    PAIS VARCHAR(255),
    EMAIL VARCHAR(255),
    REFERENCIA VARCHAR(255),
    CODIGOPOSTAL INTEGER,
    ACTIVO CHAR(1),
    REGIMENES BLOB
);

CREATE TABLE FACTURACION_FOLIOS (
    ID INTEGER NOT NULL,
    EMISOR_ID INTEGER NOT NULL,
    SERIE VARCHAR(50),
    FOLIO_INICIAL INTEGER,
    FOLIO_FINAL INTEGER,
    SIGUIENTE_FOLIO INTEGER,
    NUMERO_APROBACION VARCHAR(50) NOT NULL,
    ANO_APROBACION SMALLINT NOT NULL
);

CREATE TABLE FACTURACION_INFORMES (
    ID INTEGER NOT NULL,
    MES SMALLINT,
    ANO SMALLINT,
    GENERADO_EN TIMESTAMP,
    CONTENIDO BLOB,
    ENVIADO_EN TIMESTAMP,
    TIPO CHAR(1)
);

CREATE TABLE FACTURAS (
    ID INTEGER NOT NULL,
    SERIE VARCHAR(50),
    FOLIO_ID INTEGER NOT NULL,
    GENERADA_EN TIMESTAMP NOT NULL,
    TRANSACCION_DE TIMESTAMP,
    FACTURACION_CLIENTE_ID INTEGER NOT NULL,
    FACTURACION_EMISOR_ID INTEGER NOT NULL,
    VENTATICKET_ID INTEGER,
    VENTATICKET_FOLIO INTEGER,
    SUBTOTAL FLOAT,
    IMPUESTOS FLOAT,
    TOTAL FLOAT,
    XML BLOB NOT NULL,
    CANCELADA_EN TIMESTAMP,
    TIPO CHAR(1),
    CERTIFICADO_ID INTEGER,
    TURNO_ID INTEGER,
    VERSION_CFD VARCHAR(4),
    UUID VARCHAR(38),
    TIMBRADA_EN TIMESTAMP,
    PAC VARCHAR(3),
    SE_MANDO_TIMBRAR_EN TIMESTAMP,
    SE_MANDO_CANCELAR_EN TIMESTAMP,
    EXTRAS_POR_ARTICULO BLOB,
    ACUSE_CANCELACION VARCHAR(3000),
    FOLIO INTEGER,
    ABONO_ID INTEGER,
    FACTURA_RELACIONADA_ID INTEGER,
    IMPUESTOS_LOCALES NUMERIC,
    ESTADO VARCHAR(2),
    CLIENTESV2_FACTURACION_ID INTEGER,
    IMPUESTOS_RETENIDOS NUMERIC
);

CREATE TABLE FACTURAS_ABONOS (
    FACTURA_ID INTEGER NOT NULL,
    ABONO_ID INTEGER NOT NULL,
    FACTURA_PADRE_ID INTEGER NOT NULL
);

CREATE TABLE HISTORIAL_INVENTARIO (
    ID INTEGER NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    CUANDO_FUE TIMESTAMP NOT NULL,
    TIPO CHAR(1) NOT NULL,
    HABIA FLOAT,
    CANTIDAD FLOAT NOT NULL,
    CODIGO_PRODUCTO VARCHAR(20) NOT NULL,
    CAJA_ID INTEGER,
    TURNO_ID INTEGER
);

CREATE TABLE HISTORIAL_USUARIOS (
    ID INTEGER NOT NULL,
    USUARIO_ID INTEGER,
    CUANDO TIMESTAMP,
    CAJA_ID INTEGER,
    MOVIMIENTO VARCHAR(255)
);

CREATE TABLE IMPUESTOS (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    PORCENTAJE FLOAT,
    DEFECTO CHAR(1),
    ACTIVO CHAR(1),
    ORIGEN CHAR(1) NOT NULL,
    BASE_GRAVABLE CHAR(1),
    TIPO CHAR(1) NOT NULL
);

CREATE TABLE IMPUESTOS_REGLAS (
    ID INTEGER NOT NULL,
    IMPUESTO_ID INTEGER NOT NULL,
    RECEPTOR_CLAVE_REGIMEN VARCHAR(50),
    TIPO_CONTRIBUYENTE VARCHAR(50)
);

CREATE TABLE INVENTARIO_AJUSTES (
    ID INTEGER NOT NULL,
    FOLIO INTEGER NOT NULL,
    CUANDO_FUE TIMESTAMP NOT NULL,
    PRODUCTO_ID INTEGER NOT NULL,
    CANTIDAD FLOAT NOT NULL,
    COSTO_UNITARIO FLOAT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    CAJA_ID INTEGER,
    USUARIO_ID INTEGER,
    ALMACEN_ID INTEGER
);

CREATE TABLE INVENTARIO_APARTADO (
    PRODUCTO_ID INTEGER NOT NULL,
    CANTIDAD_APARTADA FLOAT NOT NULL,
    TICKET_ID INTEGER,
    CAJA_ID INTEGER
);

CREATE TABLE INVENTARIO_BALANCES (
    PRODUCTO_ID INTEGER NOT NULL,
    CANTIDAD_ACTUAL FLOAT,
    ALMACEN_ID INTEGER
);

CREATE TABLE INVENTARIO_HISTORIAL (
    ID INTEGER NOT NULL,
    PRODUCTO_ID INTEGER NOT NULL,
    CUANDO_FUE TIMESTAMP NOT NULL,
    CANTIDAD_ANTERIOR FLOAT NOT NULL,
    CANTIDAD FLOAT NOT NULL,
    DESCRIPCION VARCHAR(255),
    COSTO_UNITARIO FLOAT,
    COSTO_DESPUES FLOAT,
    AJUSTE_ID INTEGER,
    RECIBO_INVENTARIO_ID INTEGER,
    VENTA_ID INTEGER,
    TRANSFERENCIA_ID INTEGER,
    CAJA_ID INTEGER,
    VENTA_POR_KIT CHAR(1),
    USUARIO_ID INTEGER,
    ALMACEN_ID INTEGER
);

CREATE TABLE INVENTARIO_RECIBOS (
    ID INTEGER NOT NULL,
    FOLIO INTEGER NOT NULL,
    RECIBIDO_EN TIMESTAMP NOT NULL,
    ORDEN_DE_COMPRA_ID INTEGER,
    CAJA_ID INTEGER,
    USUARIO_ID INTEGER,
    ALMACEN_ID INTEGER
);

CREATE TABLE INVENTARIO_RECIBOS_DETALLE (
    INVENTARIO_RECIBO_ID INTEGER NOT NULL,
    SECUENCIA INTEGER NOT NULL,
    PRODUCTO_ID INTEGER NOT NULL,
    CANTIDAD_RECIBIDA FLOAT NOT NULL,
    COSTO_UNITARIO FLOAT NOT NULL
);

CREATE TABLE LISTA_DE_COMPRA (
    ID INTEGER NOT NULL,
    ID_PRODUCTO INTEGER,
    CODIGO_PRODUCTO VARCHAR(20),
    DESCRIPCION_PRODUCTO VARCHAR(255),
    DEPARTAMENTO_PRODUCTO VARCHAR(50),
    ID_PROVEEDOR_ACTUAL INTEGER,
    ULTIMO_COSTO FLOAT,
    CANTIDAD_A_ORDENAR DOUBLE PRECISION,
    AGREGADO_EN TIMESTAMP
);

CREATE TABLE MEDIDAS (
    ID INTEGER NOT NULL,
    UNIDAD_ENTEROS VARCHAR(50) NOT NULL,
    UNIDAD_FRACCIONES VARCHAR(50) NOT NULL,
    FACTOR INTEGER,
    ACTIVO CHAR(1)
);

CREATE TABLE MOVIMIENTOS (
    ID INTEGER NOT NULL,
    OPERACION_ID INTEGER NOT NULL,
    MONTO FLOAT,
    CUANDO_FUE TIMESTAMP NOT NULL,
    COMENTARIOS VARCHAR(255),
    TIPO CHAR(1) NOT NULL,
    CLIENTE_ID INTEGER,
    CAJA_ID INTEGER NOT NULL,
    CAJERO_ID INTEGER NOT NULL,
    ABONO_ID INTEGER,
    CLIENTESV2_CREDITO_ID INTEGER
);

CREATE TABLE OPERACIONES (
    ID INTEGER NOT NULL,
    DINERO_EN_CAJA FLOAT,
    TIPO_DE_CAMBIO FLOAT,
    INICIO_USUARIO_ID INTEGER NOT NULL,
    INICIO_EN TIMESTAMP NOT NULL,
    CERRO_EN TIMESTAMP,
    CAJA_ID INTEGER NOT NULL,
    ABIERTA CHAR(1),
    VENTAS FLOAT,
    SALIDAS FLOAT,
    ENTRADAS FLOAT,
    PAGOS FLOAT,
    IMPUESTOS FLOAT,
    GANANCIAS FLOAT,
    ABONO_ID INTEGER,
    INGRESOS_TARJETA FLOAT,
    INGRESOS_VALES FLOAT,
    INGRESOS_EFECTIVO FLOAT
);

CREATE TABLE ORDENES_DE_COMPRA (
    ID INTEGER NOT NULL,
    ID_PROVEEDOR INTEGER,
    FOLIO_ORDEN_PROVEEDOR VARCHAR(50),
    CREADA_EN TIMESTAMP,
    CANCELADA_EN TIMESTAMP,
    ENVIADA_EN TIMESTAMP,
    RECIBIDA_EN TIMESTAMP,
    ESTADO CHAR(1),
    UTILIDAD_ENVIADO FLOAT,
    IMPUESTOS_ENVIADO FLOAT,
    SUBTOTAL_ENVIADO FLOAT,
    TOTAL_ENVIADO FLOAT,
    UTILIDAD_RECIBIDO FLOAT,
    IMPUESTOS_RECIBIDO FLOAT,
    SUBTOTAL_RECIBIDO FLOAT,
    TOTAL_RECIBIDO FLOAT,
    NOTAS VARCHAR(1000),
    TOTAL_ARTICULOS INTEGER
);

CREATE TABLE PAGOS_MIXTOS (
    ID INTEGER NOT NULL,
    TICKET_ID INTEGER,
    ABONO_ID INTEGER,
    FORMA_DE_PAGO CHAR(1) NOT NULL,
    MONTO FLOAT NOT NULL,
    REFERENCIA VARCHAR(255),
    CLIENTE_ID INTEGER,
    CLIENTESV2_CREDITO_ID INTEGER
);

CREATE TABLE PRODUCTOS (
    ID INTEGER NOT NULL,
    CODIGO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255),
    TVENTA CHAR(1),
    PCOSTO FLOAT,
    PVENTA FLOAT,
    DEPT INTEGER,
    PROVID INTEGER,
    UMEDIDA INTEGER,
    MAYOREO FLOAT,
    IPRIORIDAD SMALLINT,
    DINVENTARIO DOUBLE PRECISION,
    DINVMINIMO DOUBLE PRECISION,
    DINVMAXIMO DOUBLE PRECISION,
    CHECADO_EN DATE,
    PORCENTAJE_GANANCIA NUMERIC,
    COMPONENTES VARCHAR(255),
    IMPUESTOS VARCHAR(255),
    PVENTA_ANTERIOR FLOAT,
    PCOSTO_ANTERIOR FLOAT,
    PMAYOREO_ANTERIOR FLOAT,
    MEDIDA_ID INTEGER,
    PFINAL FLOAT,
    PMAYOREOFINAL FLOAT,
    ES_KIT CHAR(1),
    USA_INVENTARIO CHAR(1),
    ELIMINADO_EN TIMESTAMP
);

CREATE TABLE PRODUCTOS_BASE (
    CODIGO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(255)
);

CREATE TABLE PRODUCTOS_CFDI (
    ID INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(20),
    CLAVEPRODSERV VARCHAR(50),
    CLAVEUNIDADMEDIDA VARCHAR(50)
);

CREATE TABLE PRODUCTOS_UDF_RECARGAS (
    PRODUCTO_CODIGO VARCHAR(20) NOT NULL,
    SOPORTA_TELCEL CHAR(1) NOT NULL,
    SOPORTA_MOVISTAR CHAR(1) NOT NULL,
    SOPORTA_NEXTEL CHAR(1) NOT NULL,
    SOPORTA_IUSACELL CHAR(1) NOT NULL,
    SOPORTA_UNEFON CHAR(1) NOT NULL,
    CARRIERS BLOB
);

CREATE TABLE PRODUCTOS_UDF_SERVICIOS (
    PRODUCTO_CODIGO VARCHAR(20) NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    CODIGO_INTERNO_PROVEEDOR VARCHAR(20) NOT NULL,
    SOPORTA_CONSULTA CHAR(1)
);

CREATE TABLE PRODUCTO_COMPONENTES (
    PRODUCTO_PADRE_ID INTEGER NOT NULL,
    PRODUCTO_HIJO_ID INTEGER NOT NULL,
    CANTIDAD FLOAT NOT NULL
);

CREATE TABLE PROMOCIONES_POR_CANTIDAD (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    PRODUCTO_CODIGO VARCHAR(20),
    DESDE FLOAT,
    HASTA FLOAT,
    PRECIO_PROMOCION FLOAT,
    PRECIO_PROMOCION_CON_IMPUESTOS FLOAT NOT NULL
);

CREATE TABLE PROV (
    NUM INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    TELEFONOS VARCHAR(50)
);

CREATE TABLE PROVEEDORES (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    REPRESENTANTE VARCHAR(255),
    TELEFONOS VARCHAR(255),
    CORREOS VARCHAR(255),
    PAGINA_WEB VARCHAR(50),
    NOTAS VARCHAR(1000),
    BORRADO_EN TIMESTAMP
);

CREATE TABLE PROVEEDORES_BASE (
    ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    PAGINA_WEB VARCHAR(255),
    NOTAS VARCHAR(1000)
);

CREATE TABLE REPORTE_ABONO_SERVICIOS (
    ID_TRANSACCION VARCHAR(38) NOT NULL,
    BANCO VARCHAR(50),
    CUENTA_ID VARCHAR(50),
    FOLIO VARCHAR(50),
    FOLIO_DE_PROVEEDOR VARCHAR(50),
    FOLIO_CANCELACION VARCHAR(50),
    MONTO FLOAT NOT NULL,
    ABONADO_EN TIMESTAMP,
    CANCELADO_EN TIMESTAMP,
    MENSAJE VARCHAR(255),
    CUENTA_ORIGEN VARCHAR(50),
    OTRA_INFORMACION VARCHAR(1000),
    METODO_DE_PAGO VARCHAR(100),
    REPORTADO_PREVIAMENTE SMALLINT
);

CREATE TABLE SCHEMA_DATA_INFO (
    VERSION_MIGRACION_DATOS INTEGER
);

CREATE TABLE SCHEMA_INFO (
    VERSION_DB INTEGER
);

CREATE TABLE SINCRONIZACION_NUBE (
    ID INTEGER NOT NULL,
    JSON BLOB,
    VENTA_ID INTEGER,
    TURNO_ID INTEGER,
    SEQUENCE_NUMBER VARCHAR(255),
    CREADO_EN TIMESTAMP,
    SINCRONIZADO_EN TIMESTAMP,
    MENSAJE_ERROR VARCHAR(50),
    TIPO VARCHAR(50),
    LLAVE_ID INTEGER,
    PRIORIDAD INTEGER
);

CREATE TABLE SINCRONIZACION_VENTAS (
    VENTA_ID INTEGER NOT NULL,
    SINCRONIZADO_EN TIMESTAMP,
    MENSAJE_ERROR VARCHAR(50)
);

CREATE TABLE TRANSACCIONES_MERCADOPAGO (
    ID INTEGER NOT NULL,
    PAYMENT_INTENT_ID VARCHAR(100) NOT NULL,
    VENTA_ID INTEGER,
    ABONO_ID INTEGER,
    DEVICE_ID VARCHAR(100),
    MONTO FLOAT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    RESPONSE_CODE VARCHAR(10),
    RESPONSE_MESSAGE BLOB,
    RAW_REQUEST BLOB,
    RAW_RESPONSE BLOB,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    ERROR_MESSAGE VARCHAR(255),
    PAYMENT_ID VARCHAR(100)
);

CREATE TABLE TRANSACCIONES_PROSEPAGO (
    ID INTEGER NOT NULL,
    VENTA_ID INTEGER,
    SOLICITUD_ID VARCHAR(50),
    CADENA VARCHAR(255),
    FOLIO VARCHAR(50),
    STATUS VARCHAR(50),
    DESCRIPCION VARCHAR(50),
    CORTE VARCHAR(50),
    TARJETA VARCHAR(50),
    NOMBRE VARCHAR(255),
    CORREO VARCHAR(255),
    CONCEPTO VARCHAR(255),
    REFERENCIA VARCHAR(255),
    APROBACION VARCHAR(50),
    CAUSADENEGADA VARCHAR(255),
    PARCIALIZACION VARCHAR(50),
    TIPOPLAN VARCHAR(50),
    DIFERIMIENTO VARCHAR(255),
    IMPORTE VARCHAR(50),
    FECHA TIMESTAMP,
    ABONO_ID INTEGER
);

CREATE TABLE TURNOS (
    ID INTEGER NOT NULL,
    ID_CAJA INTEGER NOT NULL,
    ID_OPERACION_INICIO INTEGER NOT NULL,
    ID_OPERACION_FIN INTEGER,
    ID_CAJERO INTEGER,
    INICIO_EN TIMESTAMP NOT NULL,
    TERMINO_EN TIMESTAMP,
    DINERO_INICIAL NUMERIC NOT NULL,
    SOSPECHOSO CHAR(1) NOT NULL,
    ACUMULADO_VENTAS NUMERIC NOT NULL,
    ACUMULADO_ENTRADAS NUMERIC,
    ACUMULADO_SALIDAS NUMERIC,
    ACUMULADO_GANANCIA NUMERIC,
    VENTAS_EFECTIVO NUMERIC,
    VENTAS_TARJETA NUMERIC,
    VENTAS_VALES NUMERIC,
    VENTAS_CREDITO NUMERIC,
    EFECTIVO_AL_CIERRE NUMERIC,
    ABONOS_EFECTIVO NUMERIC,
    DEVOLUCIONES_VENTAS_EFECTIVO NUMERIC,
    DEVOLUCIONES_VENTAS_CREDITO NUMERIC,
    DEVOLUCIONES_ABONOS_EFECTIVO NUMERIC,
    NUMERO_VENTAS INTEGER,
    DEVOLUCIONES_VENTAS_VALES NUMERIC,
    ABONOS_TARJETA NUMERIC,
    ABONOS_VALES NUMERIC,
    COMISIONES_TARJETA FLOAT,
    SINCRONIZADO_EN TIMESTAMP,
    DEVOLUCIONES_VENTAS_TARJETA NUMERIC NOT NULL,
    VENTAS_TRANSFERENCIA NUMERIC,
    ABONOS_TRANSFERENCIA NUMERIC,
    VENTAS_CHEQUE NUMERIC,
    ABONOS_CHEQUE NUMERIC,
    DEVOLUCIONES_VENTAS_TRANS NUMERIC,
    DEVOLUCIONES_VENTAS_CHEQUE NUMERIC
);

CREATE TABLE USUARIOS (
    ID INTEGER NOT NULL,
    NOMBRE_COMPLETO VARCHAR(255),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(50),
    USUARIO VARCHAR(50) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    ACTIVO CHAR(1),
    PERMISOS BLOB,
    CREATED_ON TIMESTAMP,
    CORREO VARCHAR(255),
    ESTA_EN_CAJA_ID INTEGER,
    ELIMINADO_EN TIMESTAMP
);

CREATE TABLE VENTAS (
    ID INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(20),
    CANTIDAD FLOAT,
    FECHA TIMESTAMP,
    TICKET_ID INTEGER
);

CREATE TABLE VENTATICKETS (
    ID INTEGER NOT NULL,
    FOLIO INTEGER,
    CAJA_ID INTEGER NOT NULL,
    CAJERO_ID INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    CREADO_EN TIMESTAMP,
    SUBTOTAL FLOAT,
    IMPUESTOS FLOAT,
    TOTAL FLOAT,
    GANANCIA FLOAT,
    ESTA_ABIERTO CHAR(1),
    CLIENTE_ID INTEGER,
    VENDIDO_EN TIMESTAMP,
    ES_MODIFICABLE CHAR(1),
    PAGO_CON FLOAT,
    MONEDA VARCHAR(3),
    NUMERO_ARTICULOS INTEGER,
    PAGADO_EN TIMESTAMP,
    ESTA_CANCELADO CHAR(1),
    OPERACION_ID INTEGER NOT NULL,
    OLD_TICKET_ID INTEGER,
    NOTAS BLOB,
    IMPRIMIR_NOTA CHAR(1),
    FORMA_PAGO CHAR(10),
    REFERENCIA VARCHAR(255),
    FACTURA_ID INTEGER,
    TOTAL_DEVUELTO FLOAT,
    TOTAL_AHORRADO FLOAT NOT NULL,
    TURNO_ID INTEGER,
    TIPO_DE_CAMBIO FLOAT,
    TOTAL_CREDITO FLOAT,
    NOTAS_AL_PIE BLOB,
    REFRESCAR_TICKET CHAR(1),
    TOTAL_FACTURABLE FLOAT NOT NULL,
    CLIENTESV2_ID INTEGER NOT NULL,
    CLIENTESV2_CREDITO_ID INTEGER,
    ACTIVO CHAR(1),
    IMPRIMIR_DATOS_CLIENTE CHAR(1),
    SALDO_CREDITO FLOAT NOT NULL,
    IMPUESTOS_RETENIDOS FLOAT NOT NULL
);

CREATE TABLE VENTATICKETS_ARTICULOS (
    ID INTEGER NOT NULL,
    TICKET_ID INTEGER NOT NULL,
    PRODUCTO_CODIGO VARCHAR(20) NOT NULL,
    PRODUCTO_NOMBRE VARCHAR(255) NOT NULL,
    CANTIDAD FLOAT NOT NULL,
    GANANCIA FLOAT,
    DEPARTAMENTO_ID INTEGER,
    PAGADO_EN TIMESTAMP,
    USA_MAYOREO CHAR(1),
    PORCENTAJE_DESCUENTO FLOAT,
    COMPONENTES VARCHAR(255),
    IMPUESTOS_USADOS VARCHAR(255),
    IMPUESTO_UNITARIO FLOAT,
    PRECIO_USADO FLOAT,
    CANTIDAD_DEVUELTA FLOAT,
    FUE_DEVUELTO CHAR(1),
    PORCENTAJE_PAGADO INTEGER,
    PRECIO_FINAL FLOAT,
    AGREGADO_EN TIMESTAMP,
    TOTAL_ARTICULO FLOAT
);

CREATE TABLE VENTATICKETS_IMPUESTOS (
    ID INTEGER NOT NULL,
    VENTA_ID INTEGER NOT NULL,
    IMPUESTO_ID INTEGER NOT NULL,
    IMPUESTO_PORCENTAJE FLOAT NOT NULL,
    IMPUESTO_BASE FLOAT,
    IMPUESTO_MONTO FLOAT
);

CREATE TABLE VENTA_DE_RECARGAS (
    ID INTEGER NOT NULL,
    CODIGO_ERROR VARCHAR(50),
    COMPANIA_RECARGAS VARCHAR(50) NOT NULL,
    ENVIADA_EL TIMESTAMP NOT NULL,
    CONFIRMADA_EL TIMESTAMP,
    ESTADO_DEL_PROVEEDOR VARCHAR(50),
    NUMERO_TELEFONO VARCHAR(50) NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    PROVEEDOR_FOLIO VARCHAR(50),
    PROVEEDOR_NUMERO_ORDEN VARCHAR(50),
    TRANSACCION_ID VARCHAR(50),
    TICKET_ID INTEGER
);

CREATE TABLE VENTA_RECARGA (
    ID INTEGER NOT NULL,
    CARRIER VARCHAR(50) NOT NULL,
    ENVIADA_EN TIMESTAMP NOT NULL,
    MONTO SMALLINT NOT NULL,
    NUMERO_TELEFONO VARCHAR(21) NOT NULL,
    TRANSACCION_ID BIGINT NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    AUTORIZACION VARCHAR(50),
    NO_ORDEN_PROVEEDOR VARCHAR(50),
    VENTATICKET_ID INTEGER,
    RECIBIDA_EN TIMESTAMP,
    FUE_EXITOSA CHAR(1) NOT NULL,
    MENSAJE_FALLA VARCHAR(255),
    USUARIO VARCHAR(50) NOT NULL
);

CREATE TABLE VENTA_SERVICIO (
    ID INTEGER NOT NULL,
    ENVIADA_EN TIMESTAMP NOT NULL,
    CAJA_ID INTEGER NOT NULL,
    CAJERO_ID INTEGER NOT NULL,
    SUBTOTAL FLOAT NOT NULL,
    TOTAL FLOAT NOT NULL,
    COMISION FLOAT NOT NULL,
    TRANSACCION_ID VARCHAR(50) NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    USUARIO VARCHAR(50),
    NUMERO_DE_CONTRATO VARCHAR(50),
    NOMBRE_SERVICIO VARCHAR(50),
    NO_ORDEN_PROVEEDOR VARCHAR(50),
    VENTATICKET_ID INTEGER,
    RECIBIDA_EN TIMESTAMP,
    CANCELADA_EN TIMESTAMP,
    DATOS_CONCILIACION VARCHAR(264),
    IMPUESTO1TOTAL FLOAT NOT NULL,
    IMPUESTO2TOTAL FLOAT NOT NULL,
    CARGO_POR_SERVICIO FLOAT NOT NULL,
    CONCILIADA CHAR(1) NOT NULL,
    FUE_EXITOSA CHAR(1) NOT NULL,
    MENSAJE_FALLA VARCHAR(255),
    CONCILIADA_EN TIMESTAMP,
    TRANSACCION_ID_CANCELACION VARCHAR(50),
    TURNO_ID INTEGER,
    REFERENCIAS VARCHAR(1000),
    QUEDO_PENDIENTE CHAR(1),
    FALLO_POSTERIORMENTE CHAR(1),
    ERROR_CONCILIACION INTEGER,
    PROVEEDOR_TRANSACCION_ID INTEGER,
    AUTORIZACION_PROVEEDOR VARCHAR(100)
);

ALTER TABLE ABONOS_VENTAS ADD CONSTRAINT ABONOS_VENTAS_PK PRIMARY KEY (ID);
ALTER TABLE CLIENTESV2 ADD CONSTRAINT CLIENTESV2_PK PRIMARY KEY (ID);
ALTER TABLE FACTURAS_ABONOS ADD CONSTRAINT FACTURAS_ABONOS_PK PRIMARY KEY (FACTURA_ID, ABONO_ID, FACTURA_PADRE_ID);
ALTER TABLE INVENTARIO_APARTADO ADD CONSTRAINT FK_INVENTARIO_APARTADO_1 FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID);
ALTER TABLE INVENTARIO_BALANCES ADD CONSTRAINT FK_INVENTARIO_BALANCES_1 FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID);
ALTER TABLE INVENTARIO_BALANCES ADD CONSTRAINT FK_INVENTARIO_BALANCES_2 FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES (ID);
ALTER TABLE INVENTARIO_HISTORIAL ADD CONSTRAINT FK_INVENTARIO_HISTORIAL_1 FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID);
ALTER TABLE INVENTARIO_HISTORIAL ADD CONSTRAINT FK_INVENTARIO_HISTORIAL_2 FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES (ID);
ALTER TABLE INVENTARIO_RECIBOS ADD CONSTRAINT FK_INVENTARIO_RECIBOS_1 FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES (ID);
ALTER TABLE INVENTARIO_RECIBOS_DETALLE ADD CONSTRAINT FK_INVENTARIO_RECIBOS_DETALLE_1 FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID);
ALTER TABLE INVENTARIO_HISTORIAL ADD CONSTRAINT INTEG_163 PRIMARY KEY (ID);
ALTER TABLE INVENTARIO_RECIBOS ADD CONSTRAINT INTEG_169 PRIMARY KEY (ID);
ALTER TABLE INVENTARIO_AJUSTES ADD CONSTRAINT INTEG_178 PRIMARY KEY (ID);
ALTER TABLE ABONOS ADD CONSTRAINT PK_ABONOS PRIMARY KEY (ID);
ALTER TABLE ABONOS_ARTICULOS ADD CONSTRAINT PK_ABONOS_ARTICULOS PRIMARY KEY (ID);
ALTER TABLE ABONO_TICKETS ADD CONSTRAINT PK_ABONO_TICKETS PRIMARY KEY (ID);
ALTER TABLE ALMACENES ADD CONSTRAINT PK_ALMACENES PRIMARY KEY (ID);
ALTER TABLE ARTICULOS_DE_OC ADD CONSTRAINT PK_ARTICULOS_DE_OC PRIMARY KEY (ID);
ALTER TABLE CACHE ADD CONSTRAINT PK_CACHE PRIMARY KEY (ID);
ALTER TABLE CAJAS ADD CONSTRAINT PK_CAJAS PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ABONOS_ARTICULOS ADD CONSTRAINT PK_CA_ARTICULOS_ID PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ABONOS_IMPUESTOS ADD CONSTRAINT PK_CA_IMPUESTOS_ID PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ABONOS_PAGOS ADD CONSTRAINT PK_CA_PAGOS_ID PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ABONOS_VENTAS ADD CONSTRAINT PK_CA_VENTAS_ID PRIMARY KEY (ID);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (NUMERO);
ALTER TABLE CLIENTESV2_CREDITO ADD CONSTRAINT PK_CLIENTESV2_CREDITO_ID PRIMARY KEY (CLIENTESV2_ID);
ALTER TABLE CLIENTESV2_FACTURACION ADD CONSTRAINT PK_CLIENTESV2_FACTURACION_ID PRIMARY KEY (CLIENTESV2_ID);
ALTER TABLE COMISIONES_TARJETA ADD CONSTRAINT PK_COMISIONES_TARJETA PRIMARY KEY (ID);
ALTER TABLE CONCILIACION_PAGO_SERVICIOS ADD CONSTRAINT PK_CONCILIACION_PAGO_SERVICIOS PRIMARY KEY (ID);
ALTER TABLE CONFIGURACION ADD CONSTRAINT PK_CONFIGURACION PRIMARY KEY (ID);
ALTER TABLE CORTE_IMPUESTOS_COBRADOS ADD CONSTRAINT PK_CORTE_IMPUESTOS_COBRADOS PRIMARY KEY (ID);
ALTER TABLE CORTE_IMP_COBRADOS_OPERACION ADD CONSTRAINT PK_CORTE_IMP_COBRADOS_OPERACION PRIMARY KEY (ID);
ALTER TABLE CORTE_MOVIMIENTOS ADD CONSTRAINT PK_CORTE_MOVIMIENTOS PRIMARY KEY (ID);
ALTER TABLE CORTE_OPERACIONES ADD CONSTRAINT PK_CORTE_OPERACIONES PRIMARY KEY (ID);
ALTER TABLE CORTE_VENTAS_DEPTO_OPERACIONES ADD CONSTRAINT PK_CORTE_VENTAS_DEPTO_OPERACION PRIMARY KEY (ID);
ALTER TABLE CORTE_VENTAS_POR_DEPTO ADD CONSTRAINT PK_CORTE_VENTAS_POR_DEPTO PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ABONOS ADD CONSTRAINT PK_CREDITOS_ABONOS_ID PRIMARY KEY (ID);
ALTER TABLE CREDITOS_TRANSACCIONES ADD CONSTRAINT PK_CREDITOS_TRANSACCIONES_ID PRIMARY KEY (ID);
ALTER TABLE CREDITOS_ARTICULOS_IMPUESTOS ADD CONSTRAINT PK_CRED_ARTS_IMPUESTOS_ID PRIMARY KEY (ID);
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (ID);
ALTER TABLE DEPTS ADD CONSTRAINT PK_DEPTS PRIMARY KEY (NUM);
ALTER TABLE DEVOLUCIONES ADD CONSTRAINT PK_DEVOLUCIONES PRIMARY KEY (ID);
ALTER TABLE DEVOLUCIONES_ARTICULOS ADD CONSTRAINT PK_DEVOLUCIONES_ARTICULOS PRIMARY KEY (ID);
ALTER TABLE DEVOLUCIONES_MERCADOPAGO ADD CONSTRAINT PK_DEVOLUCIONES_MP PRIMARY KEY (ID);
ALTER TABLE FACTURACION_CERTIFICADOS ADD CONSTRAINT PK_FACTURACION_CERTIFICADOS PRIMARY KEY (ID);
ALTER TABLE FACTURACION_CLIENTES ADD CONSTRAINT PK_FACTURACION_CLIENTES PRIMARY KEY (ID);
ALTER TABLE FACTURACION_EMISORES ADD CONSTRAINT PK_FACTURACION_EMISORES PRIMARY KEY (ID);
ALTER TABLE FACTURACION_FOLIOS ADD CONSTRAINT PK_FACTURACION_FOLIOS PRIMARY KEY (ID);
ALTER TABLE FACTURACION_INFORMES ADD CONSTRAINT PK_FACTURACION_INFORMES PRIMARY KEY (ID);
ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (ID);
ALTER TABLE HISTORIAL_INVENTARIO ADD CONSTRAINT PK_HISTORIAL_INVENTARIO PRIMARY KEY (ID);
ALTER TABLE HISTORIAL_USUARIOS ADD CONSTRAINT PK_HISTORIAL_USUARIOS PRIMARY KEY (ID);
ALTER TABLE IMPUESTOS ADD CONSTRAINT PK_IMPUESTOS PRIMARY KEY (ID);
ALTER TABLE IMPUESTOS_REGLAS ADD CONSTRAINT PK_IMPUESTOS_REGLAS PRIMARY KEY (ID);
ALTER TABLE LISTA_DE_COMPRA ADD CONSTRAINT PK_LISTA_DE_COMPRA PRIMARY KEY (ID);
ALTER TABLE MEDIDAS ADD CONSTRAINT PK_MEDIDAS PRIMARY KEY (ID);
ALTER TABLE MOVIMIENTOS ADD CONSTRAINT PK_MOVIMIENTOS PRIMARY KEY (ID);
ALTER TABLE SINCRONIZACION_VENTAS ADD CONSTRAINT PK_NUBE_DELTA PRIMARY KEY (VENTA_ID);
ALTER TABLE OPERACIONES ADD CONSTRAINT PK_OPERACIONES PRIMARY KEY (ID);
ALTER TABLE ORDENES_DE_COMPRA ADD CONSTRAINT PK_ORDENES_DE_COMPRA PRIMARY KEY (ID);
ALTER TABLE PAGOS_MIXTOS ADD CONSTRAINT PK_PAGOS_MIXTOS PRIMARY KEY (ID);
ALTER TABLE PRODUCTOS_BASE ADD CONSTRAINT PK_PRODUCTOS_BASE PRIMARY KEY (CODIGO);
ALTER TABLE PRODUCTOS_CFDI ADD CONSTRAINT PK_PRODUCTOS_CFDI PRIMARY KEY (ID);
ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS_ID PRIMARY KEY (ID);
ALTER TABLE PRODUCTOS_UDF_RECARGAS ADD CONSTRAINT PK_PRODUCTOS_UDF_RECARGAS PRIMARY KEY (PRODUCTO_CODIGO);
ALTER TABLE PRODUCTOS_UDF_SERVICIOS ADD CONSTRAINT PK_PRODUCTOS_UDF_SERVICIOS PRIMARY KEY (PRODUCTO_CODIGO);
ALTER TABLE PROMOCIONES_POR_CANTIDAD ADD CONSTRAINT PK_PROMOCIONES_POR_CANTIDAD PRIMARY KEY (ID);
ALTER TABLE PROV ADD CONSTRAINT PK_PROV PRIMARY KEY (NUM);
ALTER TABLE PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID);
ALTER TABLE PROVEEDORES_BASE ADD CONSTRAINT PK_PROVEEDORES_BASE PRIMARY KEY (ID);
ALTER TABLE REPORTE_ABONO_SERVICIOS ADD CONSTRAINT PK_REPORTE_ABONO_SERVICIO PRIMARY KEY (ID_TRANSACCION);
ALTER TABLE SINCRONIZACION_NUBE ADD CONSTRAINT PK_SINCRONIZACION_NUBE PRIMARY KEY (ID);
ALTER TABLE TRANSACCIONES_MERCADOPAGO ADD CONSTRAINT PK_TRANSACCIONES_MP PRIMARY KEY (ID);
ALTER TABLE TURNOS ADD CONSTRAINT PK_TURNOS PRIMARY KEY (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID);
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (ID);
ALTER TABLE VENTATICKETS ADD CONSTRAINT PK_VENTATICKETS PRIMARY KEY (ID);
ALTER TABLE VENTATICKETS_ARTICULOS ADD CONSTRAINT PK_VENTATICKETS_ARTICULOS PRIMARY KEY (ID);
ALTER TABLE VENTATICKETS_IMPUESTOS ADD CONSTRAINT PK_VENTATICKETS_IMPUESTOS_ID PRIMARY KEY (ID);
ALTER TABLE VENTA_DE_RECARGAS ADD CONSTRAINT PK_VENTA_DE_RECARGAS PRIMARY KEY (ID);
ALTER TABLE VENTA_RECARGA ADD CONSTRAINT PK_VENTA_RECARGA PRIMARY KEY (ID);
ALTER TABLE VENTA_SERVICIO ADD CONSTRAINT PK_VENTA_SERVICIO PRIMARY KEY (ID);